image: node:alpine

pages:
  stage: build
  script:
    - apk add rsync openssh
    - npm install
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  only:
    - master
  artifacts:
    paths:
      - public
