image: node:16

before_script:
  - npm ci
pages:
  script:
    - npm run build
    - mkdir -p content
    - cp -r dist/* content/
    - mv content dist/
    - mv dist/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
